site_name: TeleCart Документация
site_url: https://nikitakiselev.github.io/telecart-docs/

nav:
  - index.md
  - install.md
  - telegram.md
  - update.md
  - uninstall.md
  - contacts.md
  - architecture.md

theme:
  name: material
  language: ru
  features:
    - glightbox
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.sections
    - toc.follow
    - toc.integrate
    - navigation.top
    - search.highlight

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.blocks.caption
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-skip-class-name
      auto_caption: false
      caption_position: bottom
      background: white
      shadow: true
      manual: false